version: '3.8'

services:
  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: ./FeedbackService
    container_name: springboot_app
    depends_on:
      - db
      - mail
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Ensure the application is configured to use the correct hostname for the mail server
      SPRING_MAIL_HOST: mail
      SPRING_MAIL_PORT: 1025
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:8090
    container_name: react_frontend
    ports:
      - "5173:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
