server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback-service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  access:
    expiration: 86400000
  refresh:
    expiration: 604800000
  secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970






#logging:
#  level:
#    org.springframework: DEBUG
